// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/lib/env';
import { supabaseSecureStorage } from '@/lib/secureStorage';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(env.supabase.url, env.supabase.publishableKey, {
  auth: {
    storage: supabaseSecureStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Security: Detect session from URL only on sign-in pages
    detectSessionInUrl: window.location.pathname.includes('/auth'),
    // Security: Flow type for better security
    flowType: 'pkce'
  }
});